### ISSUE TITLE
The release2 branch is not downloadable from comma.ai

### ISSUE THREAD

**Issue by rubixhacker** [commaai/chffrplus#10]
The readme has not been updated to reflect where v0.5.4 of chffrplus can be downloaded. The readme points to https://chffrplus.comma.ai but that is where v0.4.7.2 is deployed.

**Comment by energee** [comment]
https://github.com/commaai/chffrplus/tree/release2

**Comment by rubixhacker** [comment]
When I try to enter that directly on the EON during setup I get "Download failed"

**Comment by energee** [comment]
you can use https://chffrplus.comma.ai, it actually comes installed by default

**Comment by vanillagorillaa** [comment]
0.5.4 is now the default when downloading from chffrplus.comma.ai. You can close this issue now

**Comment by clouddumingchao** [comment]
> 0.5.4 is now the default when downloading from chffrplus.comma.ai. You can close this issue now

0.4.7.2 is now the default when downloading from chffrplus.comma.ai，please updata。thanks
