### ISSUE TITLE
Google login broken

### ISSUE THREAD

**Issue by tylergets** [commaai/chffrplus#9]
Problem was fixed in open pilot but not chffrplus, openpilot fix here:
https://github.com/commaai/openpilot/pull/357/files

**Comment by vanillagorillaa** [comment]
Fixed in latest commit, https://github.com/commaai/chffrplus/commit/58fda0979bb3146690348da59084e71635deac59

**Comment by MarkVLK** [comment]
Any chance we could get that pushed to `release2` branch as well? I seem to be unable to sign in still.

**Comment by vanillagorillaa** [comment]
This is fixed on both branches, this issue can be closed now
